### ISSUE TITLE
Sparse Partial Least Squares Regression

### ISSUE THREAD

**Issue by melvinev** [olivertomic/hoggorm#17]
Have you thought about implementing this? 

Thank you for the package!

https://cran.r-project.org/web/packages/spls/spls.pdf

http://mixomics.org/methods/spls/

**Comment by olivertomic** [comment]
Dear melvinev,

thank you for your interest in hoggorm. spls would be a nice addition to hoggorm sometime in the future, but for the time being the greatest limitation is human resources. For the moment we are rather focusing releasing SO-PLS (https://onlinelibrary.wiley.com/doi/abs/10.1002/cem.1357) in an own package for data consisting of muliple blocks. But if you would be interested in contributing spls, we'd gladly welcome your effort.

**Comment by StevenLi-DS** [comment]
Hi, @olivertomic. Really thank you for the package since it provides very comprehensive statistics. Could you suggest some resources/material for PLS2 regression?

**Comment by olivertomic** [comment]
Hi @StevenLi-DS 
I am glad to hear that you find hoggorm useful. There is plenty of literature out there discussing PLS2 depending on your interests. Here are a couple of good ones:

https://personal.utdallas.edu/~herve/Abdi-PLSR2007-pretty.pdf
https://personal.utdallas.edu/~herve/abdi-wireCS-PLS2010.pdf

Hope you find those useful.

**Comment by StevenLi-DS** [comment]
Dear @olivertomic 
Thanks for the paper! I've read some papers, and the doc as well as the example notebook you provided for PLSR2. I'm in a social science field. I have many Y response variables measuring health outcome and some X variables measuring demographics. I'm still a little bit confused by some statistics. 

I used a sample dataset from seaborn. Could you please take a look at the following notebook?
[plsr2_example.zip](https://github.com/olivertomic/hoggorm/files/3640204/plsr2_example.zip)
