### ISSUE TITLE
individual plotting issue

### ISSUE THREAD

**Issue by Mohamed0gad** [olivertomic/hoggorm#28]
Dear sir ,

first let me thank you for this great effort and good work, in short I have applied PCR model to X and Y data sets and every thing is OK also when I applied:
hop.plot(model, comp=[1, 2], plots=[1, 2, 3, 4, 6], objNames=Xsamples, XvarNames=wl,YvarNames=Analytes)
also every thing was normally shown
only when I have applied:
hop.explainedVariance(model, which='X')

Then I have got that error:

TypeError                                 Traceback (most recent call last)
<ipython-input-96-6742670380d6> in <module>
----> 1 hop.explainedVariance(model, which=X)

~\Anaconda3\lib\site-packages\hoggormplot\conv_explainedVariancePlot.py in explainedVariance(model, which, cummulative, individual, validated, figsize)
     55     plot(model, plots='explainedVariance', which=which,
     56                  cummulative=cummulative, individual=individual, validated=validated,
---> 57                  figsize=figsize)
     58 
     59 

TypeError: plot() got an unexpected keyword argument 'cummulative'

I appreciate if you can help me solve that.

thanks

**Comment by olivertomic** [comment]
Hi Mohamed,

thanks a lot for reporting this. This issue should be fixed in the latest version of the hoggormPlot package (v0.13.2) which I uploaded to pypi.org today.  Please update also hoggorm (also v0.13.2).

Oliver

**Comment by Mohamed0gad** [comment]
Dear Olver, 

Thanks  for your fast response and for the new versions, I will try again.

I have used the hoggorm package to develop a variable selection script using value of regression coefficients for each variable  and cost function " mean square error" of PCR model.
The idea is not mine, I found it  [here](https://www.idtools.com.au/variable-selection-method-pls-python/) applied to PLS models. therefore I tried to apply the same idea to PCR also. I have Jupiter notebook if you don't mind to  review  this small project please tell me and I will send it to you. As I am of one month only knowledge in python and I think it may contain major issues I cant realize. Also, I am new to GitHub so I don't know how to share it here if you liked to participate in such small project send me your email. 

Best regards,
Mohamed
