### ISSUE TITLE
How to save hoggorm plot or to be specific write it to a pdf?

### ISSUE THREAD

**Issue by alphomeg** [olivertomic/hoggorm#29]
Hello,
i'm working on a project and need to save the hoggorm plot to pdf please help me in this regard.

**Comment by olivertomic** [comment]
Hi @alphomeg ,

to save your plot as PDF, follow these steps:

Click on the save-button in the plot menu

![hoggorm_plot_menu](https://user-images.githubusercontent.com/391156/87646499-3a23f400-c74f-11ea-8e73-cbdcc3537f51.JPG)

Then save the plot in the format you want (for example as PDF)

![select_pdf](https://user-images.githubusercontent.com/391156/87646866-6b042900-c74f-11ea-97d8-59d6283894c1.JPG)

Hopefully, this works for you. 

Oliver

**Comment by alphomeg** [comment]
Thank you for your response. 
I want to automate the process. Along with graph i want to save the full report as pdf is there any solution like in the matplotlib

plt.save_pdf(‘graph.pdf’)

Awaiting your response. 

Regards,
Aqib Hameed

**Comment by olivertomic** [comment]
Unfortunately there is no option for automated saving. This could be a nice addition to a future version of hoggormplot. However, you could do the following for a manual workaround:

1. open file named main_plot.py (part of the hoggorm package), wherever it is located on your computer
2. after every command plt.show() (should be nine in total) add command plt.savefig("myplotname.pdf", bbox_inches='tight')

This should save every plot you generate into your work folder. I hope that helps.

Oliver

**Comment by alphomeg** [comment]
Hi,
Yes thank you. 
Instead of that i was thinking of supplying plt as an argument to plot functions in this way i can write other things in the pdf. 
Thank you for your response. 

Regards,
Aqib Hameed
