### ISSUE TITLE
R2 and R2adjusted for PCR?

### ISSUE THREAD

**Issue by andife** [olivertomic/hoggorm#30]
Hello,
thank you for the nice package, and the possibility of nice visualizations.

I have the following question. Is it possible to specify an R2 or R2adjusted in the PCR.
And is a kind of regression-summary function (like e.g. statsmodel) planned?

If it is already in the package and I missed it, I would appreciate a short note.

(In my personal current use case, I'm interested how R2adjusted changes by adding more principal components to the regression)

Thank you

Andi

**Comment by olivertomic** [comment]
Hi @andife and sorry about the late reply. I forgot about this one. With PCR (as with PLSR) the R2 is what we call the **calibrated** explained variance in percent. The best way to identify the optimal number of components is to study the **validated** explained variance of the model. In general, as long as the validated explained variance increases for each component it is safe to include the additional component. 

But one should be careful if samples in the model are few and very different from each other. This would lead to very different models when leaving out one sample during cross-validation and making the model based on the remaining samples. In such situations, errors may be very high when projecting the left-out sample onto the new model with fewer samples.
