### ISSUE TITLE
Link in github to "BSD-License" not working

### ISSUE THREAD

**Issue by andife** [olivertomic/hoggorm#31]
The link 
![image](https://user-images.githubusercontent.com/20612932/94346148-07d62300-002b-11eb-8372-170d0aa4306b.png)
in grey "BSD-License" did not work
It points to https://github.com/yngvem/hoggorm/blob/master/LICENSE

**Comment by olivertomic** [comment]
Thanks for raising this issue, @andife. This fixed now.
