### ISSUE TITLE
Info: trying to add the package to conda-forge

### ISSUE THREAD

**Issue by andife** [olivertomic/hoggorm#33]
Hello,
to get to know and find out how a conda-forge recipe works, I'm trying to add your nice package there...
https://github.com/conda-forge/staged-recipes/pull/12736

Thank you for the package
Andi

**Comment by olivertomic** [comment]
You are welcome to contribute by compiling a conda package. Please let me know when your are done, the I can add more installation instructions.

**Comment by andife** [comment]
It probably worked ...
https://github.com/conda-forge/hoggorm-feedstock

=> now I'll try hoggormplot

**Comment by olivertomic** [comment]
That's excellent! Thank you for making the package. I'll try to install and test it as soon as I can. It would be fun to have both packages available at conda forge.
