### ISSUE TITLE
numpy version (1.9 or 1.11.3)?

### ISSUE THREAD

**Issue by andife** [olivertomic/hoggorm#35]
In my opinion,  an inconstancy according to numpy exists

(base) andi@pc1:~/work/hoggorm$ grep -H -C 2 "numpy" *
grep: docs: Ist ein Verzeichnis
grep: examples: Ist ein Verzeichnis
grep: hoggorm: Ist ein Verzeichnis
README.rst-.. _Anaconda distribution: https://www.anaconda.com/download/
README.rst-
README.rst:- numpy >= 1.9
README.rst-
README.rst-Installation
--
requirements.txt:numpy >= 1.11.3
--
setup.cfg-packages = find:
setup.cfg-install_requires =
setup.cfg:	numpy>=1.9
setup.cfg-setup_requires =
setup.cfg-	Sphinx
grep: tests: Ist ein Verzeichnis

**Comment by olivertomic** [comment]
Thanks for pointing this out. This is fixed now.
